In [1]:
import tensorflow as tf
print(tf.__version__)

print('GPU name: {}'.format(tf.test.gpu_device_name()))

2.0.0
GPU name: 


# Sequence modelling 

## Coding tutorials
 #### 1.  The IMDb dataset
 #### 2. Padding and masking sequence data
 #### 3. The `Embedding` layer
 #### 4. The Embedding Projector
 #### 5. Recurrent neural network layers
 #### 6. Stacked RNNs and the `Bidirectional` wrapper

***
<a id="coding_tutorial_1"></a>
## The IMDb Dataset

#### Load the IMDB review sentiment dataset

In [2]:
# Import imdb

import tensorflow.keras.datasets.imdb as imdb

In [3]:
# Download and assign the data set using load_data()

(x_train, y_train), (x_test, y_test) = imdb.load_data()

C:\Users\jymch\anaconda3\lib\site-packages\tensorflow_core\python\keras\datasets\imdb.py:129: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_train, y_train = np.array(xs[:idx]), np.array(labels[:idx])
C:\Users\jymch\anaconda3\lib\site-packages\tensorflow_core\python\keras\datasets\imdb.py:130: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x_test, y_test = np.array(xs[idx:]), np.array(labels[idx:])


#### Inspect the dataset

In [4]:
# Inspect the type of the data

type(x_train)

numpy.ndarray

In [5]:
# Inspect the shape of the data

x_train.shape

(25000,)

In [6]:
# Display the first dataset element input
# Notice encoding

x_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [7]:
# Display the first dataset element output

y_train[0]

1

#### Load dataset with different options

In [8]:
# Load the dataset with defaults
imdb.load_data(path = 'imdb.npz',
               index_from=3)

# ~/.keras/dataset/

((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [9]:
# Limit the vocabulary to the top 500 words using num_words

imdb.load_data(num_words=500)

((array([list([1, 14, 22, 16, 43, 2, 2, 2, 2, 65, 458, 2, 66, 2, 4, 173, 36, 256, 5, 25, 100, 43, 2, 112, 50, 2, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 2, 2, 17, 2, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2, 19, 14, 22, 4, 2, 2, 469, 4, 22, 71, 87, 12, 16, 43, 2, 38, 76, 15, 13, 2, 4, 22, 17, 2, 17, 12, 16, 2, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2, 2, 16, 480, 66, 2, 33, 4, 130, 12, 16, 38, 2, 5, 25, 124, 51, 36, 135, 48, 25, 2, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 2, 15, 256, 4, 2, 7, 2, 5, 2, 36, 71, 43, 2, 476, 26, 400, 317, 46, 7, 4, 2, 2, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2, 56, 26, 141, 6, 194, 2, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 2, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 2, 88, 12, 16, 283, 5, 16, 2, 113, 103, 32, 15, 16, 2, 19, 178, 32]),
         list([1, 194, 2, 194, 2, 78, 228, 5, 6, 2, 2, 2, 134, 26, 4, 2, 8, 118, 2, 14, 394, 20, 13, 119, 2, 189, 102, 5, 207, 110, 2, 

In [10]:
# Ignore the top 10 most frequent words using skip_top

imdb.load_data(num_words=500, skip_top=10, oov_char=2)

((array([list([2, 14, 22, 16, 43, 2, 2, 2, 2, 65, 458, 2, 66, 2, 2, 173, 36, 256, 2, 25, 100, 43, 2, 112, 50, 2, 2, 2, 35, 480, 284, 2, 150, 2, 172, 112, 167, 2, 336, 385, 39, 2, 172, 2, 2, 17, 2, 38, 13, 447, 2, 192, 50, 16, 2, 147, 2, 19, 14, 22, 2, 2, 2, 469, 2, 22, 71, 87, 12, 16, 43, 2, 38, 76, 15, 13, 2, 2, 22, 17, 2, 17, 12, 16, 2, 18, 2, 2, 62, 386, 12, 2, 316, 2, 106, 2, 2, 2, 2, 16, 480, 66, 2, 33, 2, 130, 12, 16, 38, 2, 2, 25, 124, 51, 36, 135, 48, 25, 2, 33, 2, 22, 12, 215, 28, 77, 52, 2, 14, 407, 16, 82, 2, 2, 2, 107, 117, 2, 15, 256, 2, 2, 2, 2, 2, 2, 36, 71, 43, 2, 476, 26, 400, 317, 46, 2, 2, 2, 2, 13, 104, 88, 2, 381, 15, 297, 98, 32, 2, 56, 26, 141, 2, 194, 2, 18, 2, 226, 22, 21, 134, 476, 26, 480, 2, 144, 30, 2, 18, 51, 36, 28, 224, 92, 25, 104, 2, 226, 65, 16, 38, 2, 88, 12, 16, 283, 2, 16, 2, 113, 103, 32, 15, 16, 2, 19, 178, 32]),
         list([2, 194, 2, 194, 2, 78, 228, 2, 2, 2, 2, 2, 134, 26, 2, 2, 2, 118, 2, 14, 394, 20, 13, 119, 2, 189, 102, 2, 207, 110, 2, 

In [11]:
# Limit the sequence lengths to 500 using maxlen

imdb.load_data(maxlen=500)

((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [12]:
 # Use '1' as the character that indicates the start of a sequence

 imdb.load_data(start_char=1)

((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

#### Explore the dataset word index

In [13]:
# Load the imdb word index using get_word_index()

imdb_word_index = imdb.get_word_index()

In [14]:
# View the word index as a dictionary,
# accounting for index_from.

index_from = 3
imdb_word_index = {key:val + index_from for key, val in imdb_word_index.items()}

In [15]:
# Retrieve a specific word's index

imdb_word_index['simpsonian']

52256

In [16]:
# View an input sentence

inv_imdb_word_index = {val:key for key, val in imdb_word_index.items()}
{inv_imdb_word_index[index] for index in x_train[0] if index > index_from}

{'a',
 'actor',
 'after',
 'all',
 'also',
 'amazing',
 'an',
 'and',
 'are',
 'as',
 'at',
 'be',
 'because',
 'been',
 'being',
 'big',
 'bought',
 "boy's",
 'brilliant',
 'but',
 'came',
 'casting',
 'children',
 'congratulations',
 'connection',
 'could',
 'cried',
 'cry',
 'definitely',
 'direction',
 'director',
 "don't",
 'done',
 'end',
 'everyone',
 "everyone's",
 'fact',
 'father',
 'film',
 'fishing',
 'fly',
 'for',
 'from',
 'good',
 'great',
 'grown',
 'have',
 'i',
 'if',
 'imagine',
 'is',
 'island',
 'it',
 'just',
 'know',
 'left',
 'life',
 'list',
 'little',
 'location',
 'loved',
 'lovely',
 'much',
 'must',
 'myself',
 'norman',
 "norman's",
 'now',
 'of',
 'often',
 'out',
 'part',
 "part's",
 'paul',
 'play',
 'played',
 'praised',
 'praising',
 'profile',
 'real',
 'really',
 'recommend',
 "redford's",
 'released',
 'remarks',
 'retail',
 'robert',
 'sad',
 'same',
 'say',
 'scenery',
 'scottish',
 'shared',
 'should',
 'so',
 "someone's",
 'soon',
 'stars',
 '

In [17]:
# Get the sentiment value

y_train[0]

1

---
<a id="coding_tutorial_2"></a>
## Padding and Masking Sequence Data

In [18]:
# Load the imdb data set

import tensorflow.keras.datasets.imdb as imdb
(x_train, y_train), (x_test, y_test) = imdb.load_data()

#### Preprocess the data with padding

In [19]:
# Inspect the input data shape

x_train.shape

(25000,)

In [20]:
# Pad the inputs to the maximum length using maxlen

padded_x_train = tf.keras.preprocessing.sequence.pad_sequences(x_train, maxlen=300, padding='post', truncating = 'pre')

In [21]:
# Inspect the output data shape
padded_x_train.shape


(25000, 300)

#### Create a Masking layer

In [22]:
# Import numpy 

import numpy as np

In [23]:
# Masking expects to see (batch, sequence, features)
# Create a dummy feature dimension using expand_dims

padded_x_train = np.expand_dims(padded_x_train, -1)

In [24]:
# Create a Masking layer 

tf_x_train = tf.convert_to_tensor(padded_x_train, dtype = 'float32')
masking_layer = tf.keras.layers.Masking(mask_value = 0.0)

In [25]:
# Pass tf_x_train to it

masked_x_train = masking_layer(tf_x_train)

In [26]:
# Look at the dataset



In [27]:
# Look at the ._keras_mask for the dataset

masked_x_train._keras_mask

<tf.Tensor: id=8, shape=(25000, 300), dtype=bool, numpy=
array([[ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       ...,
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False],
       [ True,  True,  True, ..., False, False, False]])>

***
<a id="coding_tutorial_3"></a>
## The Embedding layer

#### Create and apply an `Embedding` layer

In [28]:
# Create an embedding layer using layers.Embedding
# Specify input_dim, output_dim, input_length

embedding_layer = tf.keras.layers.Embedding(input_dim = 501, output_dim = 16)

In [29]:
# Inspect an Embedding layer output for a fixed input
# Expects an input of shape (batch, sequence, feature)

sequence_of_indices = tf.constant([[[0],[1],[5],[500]]])
sequence_of_indices.shape
sequence_of_embeddings = embedding_layer(sequence_of_indices)
sequence_of_embeddings

<tf.Tensor: id=23, shape=(1, 4, 1, 16), dtype=float32, numpy=
array([[[[-0.00323147,  0.00162695,  0.03098197, -0.02245255,
          -0.0255447 ,  0.02629758, -0.02838956, -0.00330715,
           0.01086681,  0.04916295,  0.03262044, -0.03147334,
           0.03918246,  0.01753941,  0.02805651, -0.04758259]],

        [[-0.04260991,  0.0435236 ,  0.04647234, -0.00107615,
           0.02330052,  0.01602527, -0.00906334, -0.0085004 ,
           0.01052418,  0.04869344, -0.00800037, -0.00187373,
          -0.0020823 ,  0.03012669, -0.04740914, -0.02568779]],

        [[ 0.03180201,  0.04197797,  0.02399919, -0.01392909,
           0.04407927,  0.03988575, -0.01033569, -0.00686326,
          -0.01520995, -0.00085526, -0.03013209, -0.00070673,
           0.04034592, -0.02837108,  0.01296878, -0.04717388]],

        [[ 0.01688481,  0.03852667, -0.02381846,  0.01408465,
           0.03076888, -0.03952184,  0.00238558, -0.04540951,
           0.02625456, -0.02100351,  0.0289261 ,  0.02783174,

In [30]:
# Inspect the Embedding layer weights using get_weights()

embedding_layer.get_weights()

[array([[-0.00323147,  0.00162695,  0.03098197, ...,  0.01753941,
          0.02805651, -0.04758259],
        [-0.04260991,  0.0435236 ,  0.04647234, ...,  0.03012669,
         -0.04740914, -0.02568779],
        [-0.01805526, -0.00881659,  0.04915759, ..., -0.00353698,
         -0.01859536, -0.01691099],
        ...,
        [-0.03650447,  0.02437819, -0.04315187, ..., -0.01059612,
         -0.03333262,  0.04800376],
        [-0.01060253, -0.03075567, -0.01782047, ...,  0.02019816,
          0.03193018, -0.02839907],
        [ 0.01688481,  0.03852667, -0.02381846, ..., -0.02207612,
         -0.01775016, -0.02456892]], dtype=float32)]

In [31]:
# Get the embedding for the 14th index

embedding_layer.get_weights()[0][14:]

array([[ 0.00274408,  0.03416478, -0.02291639, ..., -0.04969654,
         0.04683157,  0.02846161],
       [-0.00153072,  0.04356707, -0.02800826, ...,  0.02391677,
         0.0153116 ,  0.01483694],
       [ 0.01438791,  0.01670204,  0.02803395, ..., -0.02844321,
        -0.00364991, -0.00093211],
       ...,
       [-0.03650447,  0.02437819, -0.04315187, ..., -0.01059612,
        -0.03333262,  0.04800376],
       [-0.01060253, -0.03075567, -0.01782047, ...,  0.02019816,
         0.03193018, -0.02839907],
       [ 0.01688481,  0.03852667, -0.02381846, ..., -0.02207612,
        -0.01775016, -0.02456892]], dtype=float32)

#### Create and apply an `Embedding` layer that uses `mask_zero=True`

In [32]:
# Create a layer that uses the mask_zero kwarg

masking_embedding_layer = tf.keras.layers.Embedding(input_dim = 501, output_dim = 16, mask_zero=True)

In [33]:
# Apply this layer to the sequence and see the _keras_mask property

masked_sequence_of_embedding = masking_embedding_layer(sequence_of_indices)
masked_sequence_of_embedding._keras_mask

<tf.Tensor: id=41, shape=(1, 4, 1), dtype=bool, numpy=
array([[[False],
        [ True],
        [ True],
        [ True]]])>

---
<a id="coding_tutorial_4"></a>
## The Embedding Projector

#### Mount Google Drive

In [34]:
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.colab'

#### Load and preprocess the IMDb data

In [35]:
# A function to load and preprocess the IMDB dataset

def get_and_pad_imdb_dataset(num_words=10000, maxlen=None, index_from=2):
    from tensorflow.keras.datasets import imdb

    # Load the reviews
    (x_train, y_train), (x_test, y_test) = imdb.load_data(path='imdb.npz',
                                                          num_words=num_words,
                                                          skip_top=0,
                                                          maxlen=maxlen,
                                                          start_char=1,
                                                          oov_char=2,
                                                          index_from=index_from)

    x_train = tf.keras.preprocessing.sequence.pad_sequences(x_train,
                                                        maxlen=None,
                                                        padding='pre',
                                                        truncating='pre',
                                                        value=0)
    
    x_test = tf.keras.preprocessing.sequence.pad_sequences(x_test,
                                                           maxlen=None,
                                                           padding='pre',
                                                           truncating='pre',
                                                           value=0)
    return (x_train, y_train), (x_test, y_test)

In [36]:
# Load the dataset

(x_train, y_train), (x_test, y_test) = get_and_pad_imdb_dataset()

In [37]:
# A function to get the dataset word index

def get_imdb_word_index(num_words=10000, index_from=2):
    imdb_word_index = tf.keras.datasets.imdb.get_word_index(
                                        path='imdb_word_index.json')
    imdb_word_index = {key: value + index_from for
                       key, value in imdb_word_index.items() if value <= num_words-index_from}
    return imdb_word_index

In [38]:
# Get the word index

imdb_word_index = get_imdb_word_index()

In [39]:
# Swap the keys and values of the word index

inv_imdb_word_index = {v:k for k, v in imdb_word_index.items()}

In [40]:
# View the first dataset example sentence

[inv_imdb_word_index[index] for index in x_train[0] if index>2]

['this',
 'film',
 'was',
 'just',
 'brilliant',
 'casting',
 'location',
 'scenery',
 'story',
 'direction',
 "everyone's",
 'really',
 'suited',
 'the',
 'part',
 'they',
 'played',
 'and',
 'you',
 'could',
 'just',
 'imagine',
 'being',
 'there',
 'robert',
 'is',
 'an',
 'amazing',
 'actor',
 'and',
 'now',
 'the',
 'same',
 'being',
 'director',
 'father',
 'came',
 'from',
 'the',
 'same',
 'scottish',
 'island',
 'as',
 'myself',
 'so',
 'i',
 'loved',
 'the',
 'fact',
 'there',
 'was',
 'a',
 'real',
 'connection',
 'with',
 'this',
 'film',
 'the',
 'witty',
 'remarks',
 'throughout',
 'the',
 'film',
 'were',
 'great',
 'it',
 'was',
 'just',
 'brilliant',
 'so',
 'much',
 'that',
 'i',
 'bought',
 'the',
 'film',
 'as',
 'soon',
 'as',
 'it',
 'was',
 'released',
 'for',
 'and',
 'would',
 'recommend',
 'it',
 'to',
 'everyone',
 'to',
 'watch',
 'and',
 'the',
 'fly',
 'fishing',
 'was',
 'amazing',
 'really',
 'cried',
 'at',
 'the',
 'end',
 'it',
 'was',
 'so',
 'sad',


#### Build an Embedding layer into a model

In [41]:
# Get the maximum token value

max_index_value = max(imdb_word_index.values())
max_index_value

10000

In [42]:
# Specify an embedding dimension

embedding_dim = 16

In [43]:
# Build a model using Sequential:
#     1. Embedding layer
#     2. GlobalAveragePooling1D
#     3. Dense

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim = max_index_value, output_dim = embedding_dim, mask_zero = True),
    tf.keras.layers.LSTM(16),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [44]:
# Functional API refresher: use the Model to build the same model



In [45]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 16)          160000    
_________________________________________________________________
lstm (LSTM)                  (None, 16)                2112      
_________________________________________________________________
dense (Dense)                (None, 1)                 17        
Total params: 162,129
Trainable params: 162,129
Non-trainable params: 0
_________________________________________________________________


#### Compile, train, and evaluate the model

In [46]:
# Compile the model with a binary cross-entropy loss

model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [47]:
# Train the model using .fit(), savng its history

history = model.fit(x_train, y_train, epochs = 3, batch_size = 32)

Train on 25000 samples
Epoch 1/3
25000/25000 [==============================] - 1098s 44ms/sample - loss: 0.4473 - accuracy: 0.7928
Epoch 2/3
25000/25000 [==============================] - 1086s 43ms/sample - loss: 0.2656 - accuracy: 0.8988
Epoch 3/3
25000/25000 [==============================] - 1109s 44ms/sample - loss: 0.2064 - accuracy: 0.9250


In [48]:
predictions = []
for i in range(20):
    predictions.append(model.predict(x_train[None,i,:]))

In [49]:
predictions

[array([[0.9730223]], dtype=float32),
 array([[0.01553934]], dtype=float32),
 array([[0.0185137]], dtype=float32),
 array([[0.9162119]], dtype=float32),
 array([[0.03281127]], dtype=float32),
 array([[0.5722611]], dtype=float32),
 array([[0.9794676]], dtype=float32),
 array([[0.01488411]], dtype=float32),
 array([[0.9903459]], dtype=float32),
 array([[0.3950102]], dtype=float32),
 array([[0.99602985]], dtype=float32),
 array([[0.00995571]], dtype=float32),
 array([[0.02371992]], dtype=float32),
 array([[0.01228076]], dtype=float32),
 array([[0.0354159]], dtype=float32),
 array([[0.02708852]], dtype=float32),
 array([[0.9916164]], dtype=float32),
 array([[0.7640833]], dtype=float32),
 array([[0.01131232]], dtype=float32),
 array([[0.9823607]], dtype=float32)]

In [50]:
# Plot the training and validation accuracy

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

print(history.history)

history_dict = history.history

acc      = history_dict['accuracy']
val_acc  = history_dict['val_accuracy']
loss     = history_dict['loss']
val_loss = history_dict['val_loss']

epochs = range(1, len(acc) + 1)

plt.figure(figsize=(14,5))
plt.plot(epochs, acc, marker='.', label='Training acc')
plt.plot(epochs, val_acc, marker='.', label='Validation acc')
plt.title('Training and validation accuracy')
plt.xlabel('Epoch')
plt.ylabel('Classification accuracy')
plt.legend(loc='lower right')
plt.ylim(0, 1);

{'loss': [0.4473192156267166, 0.2655914349937439, 0.20640638965845107], 'accuracy': [0.7928, 0.8988, 0.925]}


KeyError: 'val_accuracy'

#### The TensorFlow embedding projector

The Tensorflow embedding projector can be found [here](https://projector.tensorflow.org/).

In [ ]:
# Retrieve the embedding layer's weights from the trained model



In [ ]:
# Save the word Embeddings to tsv files
# Two files: 
#     one contains the embedding labels (meta.tsv),
#     one contains the embeddings (vecs.tsv)

import io
from os import path

out_v = io.open(path.join('data', 'vecs.tsv'), 'w', encoding='utf-8')
out_m = io.open(path.join('data', 'meta.tsv'), 'w', encoding='utf-8')

k = 0

for word, token in word_index.items():
    if k != 0:
        out_m.write('\n')
        out_v.write('\n')
    
    out_v.write('\t'.join([str(x) for x in weights[token]]))
    out_m.write(word)
    k += 1
    
out_v.close()
out_m.close()
# beware large collections of embeddings!

---
<a id="coding_tutorial_5"></a>
## Recurrent neural network layers

#### Initialize and pass an input to a SimpleRNN layer

In [ ]:
# Create a SimpleRNN layer and test it

simplernn_layer = tf.keras.layers.SimpleRNN(units = 16)

In [ ]:
# Note that only the final cell output is returned

sequence = tf.constant([[[1.,1.], [2.,2.], [56.,-100.]]])
layer_output = simplernn_layer(sequence)
layer_output

#### Load and transform the IMDB review sentiment dataset

In [ ]:
# A function to load and preprocess the IMDB dataset

def get_and_pad_imdb_dataset(num_words=10000, maxlen=None, index_from=2):
    from tensorflow.keras.datasets import imdb

    # Load the reviews
    (x_train, y_train), (x_test, y_test) = imdb.load_data(path='imdb.npz',
                                                          num_words=num_words,
                                                          skip_top=0,
                                                          maxlen=maxlen,
                                                          start_char=1,
                                                          oov_char=2,
                                                          index_from=index_from)

    x_train = tf.keras.preprocessing.sequence.pad_sequences(x_train,
                                                        maxlen=None,
                                                        padding='pre',
                                                        truncating='pre',
                                                        value=0)
    
    x_test = tf.keras.preprocessing.sequence.pad_sequences(x_test,
                                                           maxlen=None,
                                                           padding='pre',
                                                           truncating='pre',
                                                           value=0)
    return (x_train, y_train), (x_test, y_test)

In [ ]:
# Load the dataset

(x_train, y_train), (x_test, y_test) = get_and_pad_imdb_dataset()


In [ ]:
# A function to get the dataset word index

def get_imdb_word_index(num_words=10000, index_from=2):
    imdb_word_index = tf.keras.datasets.imdb.get_word_index(
                                        path='imdb_word_index.json')
    imdb_word_index = {key: value + index_from for
                       key, value in imdb_word_index.items() if value <= num_words-index_from}
    return imdb_word_index

In [ ]:
# Get the word index using get_imdb_word_index()

imdb_word_index = get_imdb_word_index()

#### Create a recurrent neural network model

In [ ]:
# Get the maximum index value

max_index_value = max(imdb_word_index.values())
embedding_dim = 16

In [ ]:
# Using Sequential, build the model:
# 1. Embedding.
# 2. LSTM.
# 3. Dense.

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim = max_index_value+1, # MAX_INDEX_VALUE + 1
                              output_dim = embedding_dim, mask_zero = True),
    tf.keras.layers.LSTM(16),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

#### Compile and fit the model

In [ ]:
# Compile the model with binary cross-entropy loss

model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [ ]:
# Fit the model and save its training history

history = model.fit(x_train, y_train, epochs = 3, batch_size = 32)

#### Plot learning curves

In [ ]:
# Plot the training and validation accuracy

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

history_dict = history.history

acc      = history_dict['accuracy']
val_acc  = history_dict['val_accuracy']
loss     = history_dict['loss']
val_loss = history_dict['val_loss']

epochs = range(1, len(acc) + 1)

plt.figure(figsize=(14,5))
plt.plot(epochs, acc, marker='.', label='Training acc')
plt.plot(epochs, val_acc, marker='.', label='Validation acc')
plt.title('Training and validation accuracy')
plt.xlabel('Epoch')
plt.ylabel('Classification accuracy')
plt.legend(loc='lower right')
plt.ylim(0, 1);

#### Make predictions with the model

In [ ]:
# View the first test data example sentence
# (invert the word index)

inv_imdb_word_index = {v:k for k, v in imdb_word_index.items()}

[imdb_word_index[index] for index in x_train[0] if index>2]

In [ ]:
# Get the model prediction using model.predict()

model.predict(x_test[None,0,:])

In [ ]:
# Get the corresponding label

y_test[0]

---
<a id="coding_tutorial_6"></a>
## Stacked RNNs and the Bidirectional wrapper

#### Load and transform the IMDb review sentiment dataset

In [ ]:
# A function to load and preprocess the IMDB dataset

def get_and_pad_imdb_dataset(num_words=10000, maxlen=None, index_from=2):
    from tensorflow.keras.datasets import imdb

    # Load the reviews
    (x_train, y_train), (x_test, y_test) = imdb.load_data(path='imdb.npz',
                                                          num_words=num_words,
                                                          skip_top=0,
                                                          maxlen=maxlen,
                                                          start_char=1,
                                                          oov_char=2,
                                                          index_from=index_from)

    x_train = tf.keras.preprocessing.sequence.pad_sequences(x_train,
                                                        maxlen=None,
                                                        padding='pre',
                                                        truncating='pre',
                                                        value=0)
    
    x_test = tf.keras.preprocessing.sequence.pad_sequences(x_test,
                                                           maxlen=None,
                                                           padding='pre',
                                                           truncating='pre',
                                                           value=0)
    return (x_train, y_train), (x_test, y_test)

In [ ]:
# Load the dataset

(x_train, y_train), (x_test, y_test) = get_and_pad_imdb_dataset()

In [ ]:
# A function to get the dataset word index

def get_imdb_word_index(num_words=10000, index_from=2):
    imdb_word_index = tf.keras.datasets.imdb.get_word_index(
                                        path='imdb_word_index.json')
    imdb_word_index = {key: value + index_from for
                       key, value in imdb_word_index.items() if value <= num_words-index_from}
    return imdb_word_index

In [ ]:
# Get the word index using get_imdb_word_index()

imdb_word_index = get_imdb_word_index()

#### Build stacked and bidirectional recurrent models

In [ ]:
# Get the maximum index value and specify an embedding dimension

max_index_value = max(imdb_word_index.values)
embedding_dim = 16

In [ ]:
# Using Sequential, build a stacked LSTM model via return_sequences=True

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim = max_index_value+1, # IT IS ALWAYS MAX_INDEX_VALUE + 1
                              output_dim = embedding_dim, mask_zero = True),
    tf.keras.layers.LSTM(units=32, return_sequences = True),
    tf.keras.layers.LSTM(units=32, return_sequences = False),
    tf.keras.layers.Dense(units=1, activation ='sigmoid')
])

In [ ]:
# Using Sequential, build a bidirectional RNN with merge_mode='sum'

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim = max_index_value+1, # IT IS ALWAYS MAX_INDEX_VALUE + 1
                              output_dim = embedding_dim, mask_zero = True),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(units=32), merge_mode = 'sum'),
    tf.keras.layers.Dense(units=1, activation ='sigmoid')
])

In [ ]:
# Using Sequential, build a bidirectional RNN with merge_mode='sum'

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim = max_index_value+1, # IT IS ALWAYS MAX_INDEX_VALUE + 1
                              output_dim = embedding_dim, mask_zero = True),
    tf.keras.layers.Bidirectional(layer = tf.keras.layers.LSTM(units=8), merge_mode = 'sum',
                                 backward_layer = tf.keras.layers.GRU(units = 8, go_backwards = True)),
    tf.keras.layers.Dense(units=1, activation ='sigmoid')
])

In [ ]:
# Create a model featuring both stacked recurrent layers and a bidirectional layer

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim = max_index_value+1, # IT IS ALWAYS MAX_INDEX_VALUE + 1
                              output_dim = embedding_dim),
    tf.keras.layers.Bidirectional(layer = tf.keras.layers.LSTM(units=32, return_sequences = True), merge_mode = 'concat'),
    tf.keras.layers.GRU(units = 8, return_sequences = False),
    tf.keras.layers.Dense(units=1, activation ='sigmoid')
])

#### Compile and fit the model

In [ ]:
# Compile the model

model.compile(loss='binary_crossentropy',metrics = ['accuracy'], optimizer = 'adam')

In [ ]:
# Train the model, saving its history

history = model.fit(x_train, y_train, batch_size = 32, epochs = 3)

In [ ]:
# Plot the training and validation accuracy

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')

history_dict = history.history

acc      = history_dict['accuracy']
val_acc  = history_dict['val_accuracy']
loss     = history_dict['loss']
val_loss = history_dict['val_loss']

epochs = range(1, len(acc) + 1)

plt.figure(figsize=(14,5))
plt.plot(epochs, acc, marker='.', label='Training acc')
plt.plot(epochs, val_acc, marker='.', label='Validation acc')
plt.title('Training and validation accuracy')
plt.xlabel('Epoch')
plt.ylabel('Classification accuracy')
plt.legend(loc='lower right')
plt.ylim(0, 1);